// Copyright © 2000-2022 Aipplica Systems Pte Ltd
//  
//  
//  THIS SOFTWARE IS PROVIDED BY AIPPLICA SYSTEMS PTE LIMITED ``AS IS'' AND ANY EXPRESS 
//  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
//  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL AIPPLICA SYSTEMS PTE extern "C" intERNATIONAL LIMITED
//  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
//  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
//  extern "C" intERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
//  THE POSSIBILITY OF SUCH DAMAGE.
// 

#ifdef __cplusplus
extern "C" {
#endif

int AP_CheckBusy();
int AP_InitUSB();
int AP_ReadPattern(uint8 * pptrnbfr);
int AP_ReadID(uint8 * prbuf);
int AP_ReadCal(uint8 * pptrnbfr);
int AP_WriteCalData(float coeff[7]);
int AP_ReadArray(uint8 * pptrnbfr);
int AP_ReadFrame(uint8 * pptrnbfr);
int AP_SetIntTime(uint16 inttime);
void AP_Close();

#ifdef __cplusplus
}
#endif

